### ISSUE TITLE
Connect data to components on the ecoverse page

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Client.Web#108]
## Description
As a CT user I want to the components on the ecoverse page to be driven from ecoverse data

## Acceptance criteria

- [x] Challenge tiles + panel data driven
- [x] Ecoverse panel to be data driven
-  [x] Community panel to be data driven

**Comment by Comoque1** [comment]
Shouldn't the number  of members of opportunity be added to the number of members of the challenge to this opportunity?

Opportunity members:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/4a0919af-5eda-45c5-9e5f-5ab7feccc78b)

Challenge members:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/62216215-ced5-4d61-86b6-7a43f16817ec)
