### ISSUE TITLE
Component: Community members panel

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Client.Web#111]
## Description
As a CT user I want to get a feel for the people within a particular community

## Acceptance criteria

- [ ] Tiles for a configurable amount of user
- [ ] Summary of the total number of users available
- [ ] Data driven
- [ ] If the user is not logged in then the panel should suggest that the user authenticates

**Comment by Comoque1** [comment]
Tested on DEV:

- [x] Tiles for a configurable amount of user
- [x] Summary of the total number of users available
- [x] Data driven
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/de5cdf64-3240-485d-871a-36b2cab7c6ba)
- [x] If the user is not logged in then the panel should suggest that the user authenticates - OK
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/dd6e72df-35a8-4c59-b300-52356ce39238)
