### ISSUE TITLE
Opportunity page layout

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Client.Web#140]
## Description

As a user, I want to be able to get a good understanding of the opportunity from the opportunity page

## Acceptance criteria

- [ ] Overview of the opportunity e.g. background / goals
- [ ] Details of the actor groups that have been identified within the context of the opportunity
- [ ] Details of the solution aspects
- [ ] Details of who wants to collaborate with this opportunity, both in-coming and out-going

**Comment by Comoque1** [comment]
Tested OK on Dev:

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/302884b6-2a44-4b03-a6b9-f9442cf29dc7)

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1f250bde-9d96-4584-8f5e-eac73670572b)

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b3a3ae55-3aa0-4745-8b69-15a1299cc536)

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/2768e543-e756-4a60-9c8e-3619f4155d65)

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/13d94c33-a8ac-4774-ba31-89e37e3a1d3a)

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/fba62416-1fb4-4195-ae62-508f6b44c9ae)

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/dc96751b-1d48-4360-bda6-4fd4a9005006)

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/119bb669-1643-4663-a4e2-65d951ab6636)
