### ISSUE TITLE
Predefined values for the user country field

### ISSUE THREAD

**Issue by atstojanov** [cherrytwist/Client.Web#161]
## Description

As a administrator/user
I want to be able to choose the country in the user profile from predefined list
So that no mistakes is made with the name of the country

## Acceptance criteria

- [x] country field is a combo box
- [x] there is an option to type in the contry
- [x] all [195](https://www.worldometers.info/geography/how-many-countries-are-there-in-the-world/) countries are in the list.

**Comment by Comoque1** [comment]
All countries are available for selection in user list:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/bb344156-b54e-4664-837d-e7ba713395fe)
