### ISSUE TITLE
BUG: Unable to create a new user/edit a user

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Client.Web#224]
**Describe the bug**
In testing the create new user with a space in their name, I got the following error:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/d9cd97db-1981-40de-af66-c8028fb8431a)
and then below that:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/3c87987e-7864-49ee-90ed-7f6eed930e9c)
and then this:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/4d792b7f-63f3-4ebb-85ef-f2bb1bb8cda6)

It looks like memberof is being called on a UserInput?

**To Reproduce**
Create a new user

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Comoque1** [comment]
- [x] The user is successfully created! Account and user are added correspondingly in AAD and in the DB.

- [ ] Password modal is not displayed.

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/38b960df-42ee-4edf-bc5c-cd18ccf1b55f)
