### ISSUE TITLE
Address high priority package vulnerabilities reported by npm

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Client.Web#235]
## Description

As a deployer I want to ensure that the solution I am deploying is safe

## Acceptance criteria

- [ ] Address npm package warnings about vulnerabilities
- [ ] …

**Comment by atstojanov** [comment]
There is 1 High Risk vulnerability which comes from a dependency of the react-scripts. Updating the react-scripts to its new Major version is something that is planed but may lead to unpredictable bugs. Lets do it after we go Production.

**Comment by techsmyth** [comment]
ok, agreed
