### ISSUE TITLE
Challenge is created, but references are not exposed to the client

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Client.Web#257]
## Description
As a User I want to see challenge references on the client
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0d1efd4d-b82b-4673-a457-a840d4c00f61)

[Example challenge](https://dev.cherrytwist.org/ecoverse/1/challenges/balance-test3)

## Acceptance criteria

- [ ] Challenge references are visible on the client

**Comment by OlegSubik** [comment]
Done in #259
