### ISSUE TITLE
Increase opacity on Challenge title

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Client.Web#264]
## Description

As User I want to have the opacity of (projects, github and miroboard) on challenge title increased

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e1eee274-9a9e-414e-92e8-200b0330c0a2)

## Acceptance criteria

- [ ] Opacity of (projects, github and miroboard) on challenge title increased

**Comment by OlegSubik** [comment]
In #259 the header background is reverted to be monocolored.
