### ISSUE TITLE
Remove "Remove user" from "create new user" page

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Client.Web#265]
## Description

As an Admin, I want to have "remove user" button hidden from "create new user" page
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/645add18-5ef2-4921-9234-fa540822f87f)

## Acceptance criteria

- [ ] "remove user" button hidden from "create new user" page

**Comment by OlegSubik** [comment]
not relevant anymore
