### ISSUE TITLE
BUG: Number of members is not displayed on Opportunity level

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Client.Web#272]
**Describe the bug**
Number of members is not displayed on team level
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/079d6725-3a69-44f0-b12f-9111da0af3c6)

**To Reproduce**

1. Go to [this team  page](https://acc.odyssey.ninja:3000/ecoverse/1/challenges/safe-comm/opportunities/team_15)
 - Number of members is 0
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/828707cf-60d9-485c-aff2-d13bfd59d7d6)
2. Query the members for the specific team group
```
query{
  group(ID:15){
    id
    name
    members{id name}
  }
}
```
Result shows 6 members for this team group
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/16b1dc0e-743d-4ce6-b9e5-615160228d54)

**Expected behavior**
The number of members on the client correspond to the number from the DB

**Comment by techsmyth** [comment]
Beed to chat this thru, not adding in populator & also do not have admin panel working with opportunity groups
