### ISSUE TITLE
Community panel to show members randomly

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Client.Web#281]
## Description

As a user I do not want to always see the same set of users on the home page

## Acceptance criteria

- [ ] User logos displayed in the panel to be picked randomly

## Additional Context
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/eb37840f-23d0-4161-b496-936b23aaeae5)

**Comment by Comoque1** [comment]
Should le pick user logos randomly on challenge level?

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/015a6d8c-bfc3-408a-a993-89f042e7a4b8)
