### ISSUE TITLE
Generate the .env.base file dynamically 

### ISSUE THREAD

**Issue by atstojanov** [cherrytwist/Client.Web#283]
## Description

As a developer
I want the `.env.base` file to be generated dynamically 
So that when a environment variable needs to be added or remove to do that in single place (`.env`). Otherwise mistakes are made.

## Acceptance criteria

- [ ] The `.env.base` file is auto generated

## Additional Context
The .env.base file isn't needed for development purposes. It is consumed by the docker container during the build and later on every startup of the container.

**Comment by Comoque1** [comment]
Tested on [Test environment](https://test.cherrytwist.org/ecoverse/1) OK

The following actions were performed to test the changes:
- [x] Deploy Server **dev** branch
- [x] Deploy Client.Web **client-283-2** branch - **OK**
- [x] Authenticate to the web application 
- [x] Explore all link - **OK**
