### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Client.Web#337]
## Description

As a user, I would like to be able to login as easily as possible.

## Acceptance criteria

- [ ] Login link visible on home page, that launches a separate page where users can choose between different authentication providers including the simple auth provider. This page also needs to provide a link to the register page. 

## Additional Context
Based largely on the spotify login experience

**Comment by OlegSubik** [comment]
@valentinyanakiev  Need an api to send an applicant form data

**Comment by atstojanov** [comment]
To check https://www.chromium.org/developers/design-documents/create-amazing-password-forms
