### ISSUE TITLE
BUG: browser window left open has many error msgs

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Client.Web#340]
**Describe the bug**
On leaving a window open and coming back see the following box:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/201c83f1-8b69-4593-8d94-ce40def6e59c)

**To Reproduce**

**Comment by OlegSubik** [comment]
should be fixed after merge of #318

**Comment by Comoque1** [comment]
The issue is not reproducible anymore with branch "Client.Web" "clean-up-lint"
