### ISSUE TITLE
BUG: Dev environment is not loading (loading configurations constantly)

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Client.Web#353]
**Describe the bug**
[Dev ](https://dev.cherrytwist.org/)environment is not loading  - keeps loading configurations

**To Reproduce**

1. Go to [dev env.](https://dev.cherrytwist.org/)
2. Signout and try to load the application
3. The application is not loading. System is trying to load configurations The usage of RAM is constantly increasing 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/be461f58-dee0-4f97-bd37-8f2a32568f04)

**Expected behavior**
The application is loading correctly on Edge browser. The PC memory is not increasing constantly

**Comment by Comoque1** [comment]
After cleaning the cache, the issue is not reproducible anymore

**Comment by Comoque1** [comment]
To be reevaluated

**Comment by valentinyanakiev** [comment]
It's not only on edge, I reproduced it on Chrome when I logged out and refreshed the base client URL.

**Comment by Comoque1** [comment]
Tested on [test env](https://test.cherrytwist.org/ecoverse/1) and with "Client.Web", branch "clean-up-lint", the issue is not reproducible
