### ISSUE TITLE
Client to display server metadata

### ISSUE THREAD

**Issue by OlegSubik** [cherrytwist/Client.Web#355]
- [x]  Client to display the server versions on the about page
- [x]  Client to log the server metadata to the console
- [ ]  On dev builds to display the version in more places (tbd)

**Comment by valentinyanakiev** [comment]
query
{
  metadata
  {
    services
    {
      name
      version
    }
   
  }
}

result:

{
  "data": {
    "metadata": {
      "services": [
        {
          "name": "ct-server",
          "version": "0.6.9"
        }
      ]
    }
  }
}
