### ISSUE TITLE
BUG: References could not be removed from the client

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Client.Web#363]
**Describe the bug**
User references and challenge references are not being removed, when applying changes from the client

**To Reproduce**

1. Go to the [following challenge](https://dev.cherrytwist.org/ecoverse/1/challenges/balance-grid)
2. Click on Edit context button
3. On the bottom of the page, remove a reference
4. Apply the changes - changes remain

**Note:**
1. The same applies for User references
2. There is working mutation for references removal

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/10467818-a059-4dca-9884-bf535e0d6b28)
**Expected behavior**
When reference is removed from challenge or from user, the changes is preserved

```
mutation {
      removeReference(ID:518)      
    }
```

**Comment by OlegSubik** [comment]
Whenever a client removed a ref from the form, the ContextInput will not receive the removed ref. The server should check if any refs are missing from the original context and actually remove it. 
P.S. on the ref remove click client may also call removeReference and delete ref straight away not waiting for the form submit.

**Comment by valentinyanakiev** [comment]
Currently the resolver invokes updateChallenge in ChallengeService --> updateContext in ContextService --> updateReference in ReferenceService. We deliberately had the references updates not as drop + recreate all (which is the desired behavior here) - currently we match the names of the references, if there is a match - we update the reference. If there is no match - we create new reference. We do not imply that the new set of references to be updated is the full set of references that replaces the old set.

**Comment by valentinyanakiev** [comment]
One possible solution would be to add removeReference in ContextService and if there are references deleted in the client - invoke it instead of invoking updateChallenge. If there are other fields updated - invoke first removeReference and then updateChallenge.

**Comment by valentinyanakiev** [comment]
Another possible solution is to use the removeReference API call and just provide the ID of the removed reference from the client. That might be the simplest implementation and will only require a couple of checks on the client.
