### ISSUE TITLE
Add TravisCI to Client

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Client.Web#367]
## Description

As a developer, I want to know if the code that is pending merging is going to break the build

## Acceptance criteria

- [ ] CI build on client.web?

**Comment by valentinyanakiev** [comment]
There is no TravisCI file on the client as there are no tests. Not sure why we need this.

**Comment by valentinyanakiev** [comment]
There were two differences between Client and Server at the moment:
- [x] CLA wasn't enforced on Dev on the client - fixed.
- [ ] There is no CI on the Client - there is no travisCI configuration on the Client as there are no tests. It will be pointless check at this stage in time, assuming the dev checks whether the code builds at all. We can add it if needed.

The confusion comes from the actual build->publish, but this is triggered only after merging to develop.
