### ISSUE TITLE
Manage Ecoverse Groups

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Client.Web#394]
## Description

As a CT Admin
I want to be able to edit Ecoverse groups
so that I can manage my community.

## Acceptance criteria

- [x] Edit Group --> Edit. Add a field to change the group name.
- [x] New --> Popup where you select the name of the group

**Comment by valentinyanakiev** [comment]
There is no PR for this and its in review?

**Comment by Comoque1** [comment]
The mechanism for Ecoverse groups editing will be similar to the one  for creation, using updateGroup mutation (once it is created).
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/7f6f780b-5ba5-412c-a332-917b14710277)
Closing the issue.
