### ISSUE TITLE
BUG: Token stored in application state is different from that logged to the console

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Client.Web#417]
**Describe the bug**
Log in to the client. 

There are two ways to obtain the bearer auth token:
- Console with debug msgs shown
- Application

These two tokens are now different but they used to be the same - what has changed?

**Comment by atstojanov** [comment]
They seems the same: 
![image.png](https://images.zenhubusercontent.com/5f3ccd6f7c7033ff3483f1b8/1b73eb72-b762-455f-99ec-5b100241295f)

**Comment by techsmyth** [comment]
ok, looks to be different in current builds - I saw the above on the Odyssey prod env. Can be closed.
