### ISSUE TITLE
BUG: Edit challenge doesn't work

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Client.Web#424]
**Describe the bug**
Editing a challenge always throws exceptions

**To Reproduce**

1. Go to https://dev.cherrytwist.org/admin/challenges/39/edit
2. Edit any field/
3. Click 'save'

You get 'DTO validation for class ChallengeInput { } failed! An instance of ChallengeInput has failed the validation: - property textID has failed the following constraints: isUniqueTextId'

**Comment by Comoque1** [comment]
Tested ok on [test env](https://test.cherrytwist.org/admin/challenges/5/edit)
Server version: [server-](https://github.com/cherrytwist/Server/runs/1721849323?check_suite_focus=true)
Client version: [Client.Web-429 branch](https://github.com/cherrytwist/Client.Web/runs/1721719845?check_suite_focus=true)

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/8d59b423-b942-4ff9-8d76-11a0a8408945)
