### ISSUE TITLE
BUG: Removing tags from organization, are still displayed after page refresh 

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Client.Web#439]
**Describe the bug**
 Removing tags from organization, are still displayed after page refresh

**To Reproduce**

1. Go to https://dev.cherrytwist.org/admin/organizations/
2. Create new organization
3. Edit the organization and populate all fields
4. Save the organization
5. Remove the tags
6. Save the organization
7. Refresh the page - the tags fields remain selected and populated
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b82244d0-c948-45c6-a96a-39500791e96f)

**Expected behavior**
When references are removed from organization and it is saved, after refresh, the must not be displayed.

**Comment by atstojanov** [comment]
Needs to discuss in general how arrays will be updated/merged.
