### ISSUE TITLE
Create interaction diagram for end-to-end user on-boarding

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Client.Web#450]
## Description

As an admin I want to understand all the steps involved in a user applying and joining and ecoverse

## Acceptance criteria

- [x] Interaction diagram based on draw.io
- [ ] Captures role of user, client, server, community admin, ...
- [x] Show notifications (emails) even if not implemented yet

**Comment by atstojanov** [comment]
https://drive.google.com/file/d/1d3A_CmAry93Gugw5BPRWNjJuMalPaXCA/view?usp=sharing

**Comment by techsmyth** [comment]
Very nice overview, good to chat through briefly tomorrow...
