### ISSUE TITLE
User self editing of profile

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Client.Web#452]
## Description

As a user, I want to be able to make updates to my own profile

## Acceptance criteria

- [ ] New "Profile" menu entry on the top right drop down  menu
- [ ] Profile page to display an overview of the users profile
- [ ] Allow users to update their Profile data

**Comment by atstojanov** [comment]
The use can navigate to its profile by clicking on the User Avatar. Will be nice to have it in the menu also. The profile page contains the same information (Avatar, username and roles) like the `Navbar`. In my opinion this information is unnecessary to be visible all the time. 
Current focus on the profile page is on the GROUPS. The main focus of the profile page should be user information. Groups should be mentioned in more delicate way.

- How we are going to update the avatar?
 - Should the user be allowed to upload image? 
   - If yes the image should be editable: 
     - Selecting part of the image. 
     - Image positioning.
     - Image resizing/resmpling.
  - How the uploaded image will be stored?
   - CDN
   - DB

**Comment by techsmyth** [comment]
Yep good to think through how / what is displayed once we have profile menu entry.

Re avatar, we have an epic for that - good to revisit it in this context, but may need to come after a first version of the user profile editing...
