### ISSUE TITLE
Able to assign + remove users from groups at the ecoverse and challenge level

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Client.Web#71]
## Description
As a CT community admin I want to be able to assign users into the right groups on the ecoverse and at the challenges

## Acceptance criteria

- [ ] Able to see the list of groups at the ecoverse and challenge level, if sufficiently authorised
- [ ] For each group show via some kind of visual annotation who the focal point is (if any)
- [ ] Able to see the users in each of these groups
- [ ] Able to add users to these groups, and remove users from these groups

**Comment by Comoque1** [comment]
Testing over the following test scenarios were performed against dev environment:

[Main page](https://dev.cherrytwist.org/admin)
 - [ ] **Admin** - **what is the point of the page?**
 - [x] **Users**
   - [x] Assert correct number of users is returned from the api -the one, below,  is not displayed on the client
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3cff74e9-8a38-4fad-a367-ab6366d56847)
   - [ ] **Search:**
     - [x] Search by user name  (search by string, by _, by full name) - **OK**
     - [ ] Search by user detail, (i.e. email )- **doesn't return any results**
   - [ ] **User create:**
     - [ ] Create user - **OK**
     - [ ] Verify fields:
       - [ ] avatar - **string is stored in DB**
       - [ ] In the DB there is **description** field, on the client no - **BUG??**
       - [ ] Name - **OK**
       - [ ] accountUpn - **OK**
       - [ ] firstName - **OK**
       - [ ] update is not stored - **to create BUG**
       - [ ] lastName - **OK**
       - [ ] update is not stored - **to create BUG**
       - [ ] email - **OK**
       - [ ] City, Country and Phone are not returned, when editing the user -**logged a bug**
          - [ ] phone - missing validation - **to create BUG**
        - [ ] gender - **OK**
           - [ ] lastModified - is it possible to store it to "Human date" instead to "unix epoch"
        - [ ] User password is not generated - **logged a bug**
        - [ ] Data is correctly stored  in DB - **OK**
        - [ ] Why skills are added under "science"? shouldn't we have  a  "skills" tagset? see below
          - [ ] Missing predefined skills 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/7c82d577-4dea-4dea-a5c7-f484642ebce3)
        - [ ] **User update** - none of the changes to the user is stored to the db - **create a Bug**
   -  User enhancement - could be added grid with all groups/challenges to which a user belongs
 - [ ] **Groups**
    - [ ] Assert correct number of groups/challenges is returned from the api -the one, below,  is not displayed on the client 
       - [ ] Ecoverse "members" group with Id:1 is not displayed on the client - **OK?**
    - [x] Search
       - [x] Search by groups/challenges name  (search by string, by _, by full name) - **OK**
       - [ ] Search on group level  for members is working only for name (cannot search, by email, lastName, etc..)**???**
     - [x] Add user to group - OK
     - [x] Add user to 2 groups - OK
     - [x] Add user to challenge - OK
     - [x] Add user to 2 challenges - OK
     - [x] Remove user from group - OK
     - [x] Remove user from challenge- OK
