### ISSUE TITLE
Restrict admin panel to users with <right> roles

### ISSUE THREAD

**Issue by atstojanov** [cherrytwist/Client.Web#93]
## Description
As a owner of the project
I want to restrict user with insufficient role to access the admin panel 
So that user and group management is only available to right users.

## Acceptance criteria

- [ ] Admin panel is available only to users with community-admin, ecoverse-admin or global-admin roles.

## Additional Context
User roles are determined using the memberof field from the currently logged in user via the "me" query

**Comment by Comoque1** [comment]
Tested OK on [test env](https://test.cherrytwist.org/admin/groups/ecoverse/2)
